### ISSUE TITLE
Need functionality to email admin users when new project is posted

### ISSUE THREAD

**Issue by drewwmercer** [drewwmercer/developer-ocs#58]

**Comment by sudonitesh** [comment]
I'd like to work on this

**Comment by drewwmercer** [comment]
> I'd like to work on this

That would be great!

**Comment by sudonitesh** [comment]
@drewwmercer  can you tell how to run the app. it's showing errors and there is no readme file for this

**Comment by drewwmercer** [comment]
@sudonitesh can you send the error you are seeing? It may be from the deployment last year and I need to add an issue for it if you are not able to run it locally.

**Comment by sudonitesh** [comment]
<code><pre>[hitman@BlackBox developer-ocs (master *)]$ npm start

> developer-ocs@1.0.0 start /mnt/c/Users/nitesh/Desktop/hactober/developer-ocs
> concurrently "nodemon server.js" "npm run client"

[1]
[1] > developer-ocs@1.0.0 client /mnt/c/Users/nitesh/Desktop/hactober/developer-ocs
[1] > node scripts/start-client.js
[1]
[0] [nodemon] 1.12.1
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node server.js`
[1]
[1] > mern@0.1.0 start /mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/client
[1] > react-scripts start
[1]
[1] sh: 1: react-scripts: not found
[1] npm ERR! file sh
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno ENOENT
[1] npm ERR! syscall spawn
[1] npm ERR! mern@0.1.0 start: `react-scripts start`
[1] npm ERR! spawn ENOENT
[1] npm ERR!
[1] npm ERR! Failed at the mern@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/hitman/.npm/_logs/2018-10-03T16_46_22_164Z-debug.log
[1] npm run client exited with code 0
[0] Wed, 03 Oct 2018 16:46:23 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:236:13
[0] Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:8889
[0]     at Utils.Promise.tap.then.catch.err (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:139:19)
[0]     at tryCatcher (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/util.js:16:23)
[0]     at Promise._settlePromiseFromHandler (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/promise.js:512:31)
[0]     at Promise._settlePromise (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/promise.js:569:18)
[0]     at Promise._settlePromise0 (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/promise.js:614:10)
[0]     at Promise._settlePromises (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/promise.js:689:18)
[0]     at Async._drainQueue (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/async.js:133:16)
[0]     at Async._drainQueues (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/async.js:143:10)
[0]     at Immediate.Async.drainQueues (/mnt/c/Users/nitesh/Desktop/hactober/developer-ocs/node_modules/bluebird/js/release/async.js:17:14)
[0]     at runCallback (timers.js:810:20)
[0]     at tryOnImmediate (timers.js:768:5)
[0]     at processImmediate [as _immediateCallback] (timers.js:745:5)
</pre></code>
